---
kind: Template
apiVersion: template.openshift.io/v1
labels:
  build: "${NAME}"
  template: ${NAME}-bc-template
metadata:
  name: ${NAME}
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${NAME}"
    spec:
      lookupPolicy:
        local: false
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${NAME}"
      labels:
        buildconfig: "${NAME}"
    spec:
      completionDeadlineSeconds: 600
      failedBuildsHistoryLimit: 3
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}:${VERSION}"
      postCommit: {}
      runPolicy: SerialLatestOnly
      source:
        git:
          uri: https://github.com/getredash/redash
          ref: release/10.0.x
        type: Git
        dockerfile: |-
          FROM BuildConfig
          RUN apt-get -y update && apt-get -y upgrade && apt-get clean
          
      strategy:
        sourceStrategy:
          from:
            kind: DockerImage
            name: docker.io/python:3.11.3-alpine3.17
          type: Docker
      successfulBuildsHistoryLimit: 3
      triggers:
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.
    required: true
    value: redash
  - name: VERSION
    displayName: Image version tag
    description: The version tag of the built image
    required: true
    value: latest
  - name: IMAGE_REGISTRY
    description: The base docker registry
    displayName: Docker Image Registry
    required: true
    value: image-registry.openshift-image-registry.svc:5000