---
kind: Template
apiVersion: template.openshift.io/v1
labels:
  app: ${NAME}
  app.kubernetes.io/component: ${NAME}
  app.kubernetes.io/instance: ${NAME}
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/name: redash
  app.kubernetes.io/part-of: ${NAME}
  template: ${NAME}-dc-template
metadata:
  name: ${NAME}
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${NAME}-web"
    spec:
      ports:
      - name: ${NAME}-tcp
        port: 5000
        protocol: TCP
        targetPort: 5000
      selector:
        name: "${NAME}-web"
        deploymentconfig: ${NAME}
      type: ClusterIP
      sessionAffinity: None
  - kind: Route
    apiVersion: v1
    metadata:
      name: "${NAME}-web"
    spec:
      host: "chefs-${NAME}.${DOMAIN}"
      path: "/"
      port:
        targetPort: 5000-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: "${NAME}-web"
        weight: 100
      wildcardPolicy: None
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.
    required: true
    value: redash
  - name: NAMESPACE
    description: Target namespace reference (i.e. '9f0fbe-dev')
    displayName: Namespace
    required: true
  - name: DOMAIN
    description: The base domain name of the cluster.
    displayName: Base Domain
    required: true
    value: apps.silver.devops.gov.bc.ca
  - name: IMAGE_REGISTRY
    description: The base docker registry
    displayName: Docker Image Registry
    required: true
    value: image-registry.openshift-image-registry.svc:5000
