---
kind: Template
apiVersion: template.openshift.io/v1
labels:
  app: ${NAME}
  app.kubernetes.io/component: ${NAME}
  app.kubernetes.io/instance: ${NAME}
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/name: redash
  app.kubernetes.io/part-of: ${NAME}
  template: ${NAME}-redis-dc-template
metadata:
  name: ${NAME}
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${NAME}-redis"
      labels:
        app: "${NAME}"
      annotations: {}
    spec:
      ports:
      - name: 6379-tcp
        port: 6379
        protocol: TCP
        targetPort: 6379
      selector:
        name: "${NAME}"
        deploymentconfig: "${NAME}-redis"
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "${NAME}-redis"
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        name: "${NAME}-redis"
        deploymentconfig: "${NAME}-redis"
      strategy:
        type: Recreate
        resources: {}
      triggers:
        - type: ConfigChange
      template:
        metadata:
          name: "${NAME}-redis"
          labels:
            name: "${NAME}-redis"
            deploymentconfig: "${NAME}-redis"
        spec:
          containers:
          - capabilities: {}
            env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "${NAME}-redis"
                  key: REDIS_PASSWORD
            name: redis
            image: "redis:7.0.11-alpine"
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 6379
              protocol: TCP
            readinessProbe:
              failureThreshold: 3
              initialDelaySeconds: 5
              periodSeconds: 10
              successThreshold: 1
              tcpSocket:
                port: 6379
              timeoutSeconds: 1
            resources:
              limits:
                memory: ${REDIS_MEMORY_LIMIT}
            terminationMessagePath: "/dev/termination-log"
            terminationMessagePolicy: File
            imagePullPolicy: Always
            volumeMounts:
            - name: "${NAME}-redis-volume"
              mountPath: /var/lib/redis/data
          volumes:
          - name: "${NAME}-redis-volume"
            persistentVolumeClaim:
              claimName: "${NAME}-redis"
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: "${NAME}-redis"
      labels:
        app: "${NAME}"
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "${REDIS_VOLUME_CAPACITY}"
      storageClassName: netapp-file-standard
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.
    required: true
    value: redash
  - name: NAMESPACE
    description: Target namespace reference (i.e. '9f0fbe-dev')
    displayName: Namespace
    required: true
  - name: REDIS_MEMORY_LIMIT
    displayName: Redis Memory Limit
    description: The memory limit for Redis
    required: true
    value: 512Mi
  - name: REDIS_VOLUME_CAPACITY
    displayName: Redis Volume Capacity
    description: The volume capacity for Redis
    required: true
    value: 2Gi
  - name: IMAGE_REGISTRY
    description: The base docker registry
    displayName: Docker Image Registry
    required: true
    value: image-registry.openshift-image-registry.svc:5000